name: Mirror example
on:
  push:
    branches: "main"
    paths: .github/workflows/mirror-example.yml
  schedule:
    - cron: "36 */6 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --mirror https://git.code.sf.net/p/mingw/regex .
      - run: git push --mirror "https://x:$TOKEN@github.com/actions4git/mirror-example.git"
        env:
          TOKEN: ${{ secrets.MIRROR_TRY_ME_TOKEN }}
