name: Mirror octocat/hello-world to actions4git/mirror-try-me
on:
  push:
    paths: .github/workflows/try-me.yml
  schedule:
    - cron: "36 */6 * * *"
  workflow_dispatch:
jobs:
  mirror-octocat-hello-world-to-actions4git-mirror-try-me:
    runs-on: ubuntu-latest
    steps:
      - run: git clone --bare https://github.com/octocat/hello-world.git .
      - run: git push --mirror "https://x:$TOKEN@github.com/actions4git/mirror-try-me.git"
        env:
          TOKEN: ${{ secrets.MIRROR_TRY_ME_TOKEN }}
