name: Update marketplace
on:
  push:
    branches: "main"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-marketplace:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git tag marketplace --force
      - run: git push origin marketplace --force
